// Regenerates the app icons and launch screens from the brand mark: the white
// leg on brand teal, as in frontend/public/favicon.svg (the Figma export).
// macOS only, like iOS builds. Run from mobile/: `npm run icons`.
//
//   iOS      App Store icon (1024, opaque, square: iOS rounds the corners)
//            launch image, light and dark
//   Android  adaptive icon foreground + themed-icon monochrome (vectors)
//            legacy launcher PNGs for Android 7 (API 24-25)
//            launch screen (vector tile on the canvas color, light and dark)

import AppKit

let teal = "#4BAEA7"
let canvas = (light: "#F3F7F7", dark: "#070B0B") // --rb-canvas in frontend/src/index.css

let favicon = try String(contentsOfFile: "../frontend/public/favicon.svg", encoding: .utf8)
let leg = favicon.firstMatch(of: #/<path[^>]* d="([^"]+)"/#)!.1
// The leg is 91 × 149; the favicon centers it in a 199 tile at (55, 26).
let legW = 91.0, legH = 149.0

/// The 199 × 199 brand tile. `radius` 0 is full bleed; nil is a circle.
func tile(radius: Double?) -> String {
  let shape = radius.map { #"<rect width="199" height="199" rx="\#($0)" fill="\#(teal)"/>"# } ?? #"<circle cx="99.5" cy="99.5" r="99.5" fill="\#(teal)"/>"#
  // A circle crops more of the corners, so its leg is a little smaller.
  let legT = radius == nil ? "translate(99.5 99.5) scale(0.86) translate(-45.5 -74.5)" : "translate(55 26)"
  return #"\#(shape)<path transform="\#(legT)" fill="white" d="\#(leg)"/>"#
}

func png(_ svg: String, size: Int, opaque: Bool, to path: String) throws {
  guard let image = NSImage(data: Data(svg.utf8)) else { fatalError("could not render SVG for \(path)") }
  let ctx = CGContext(
    data: nil, width: size, height: size, bitsPerComponent: 8, bytesPerRow: 0,
    space: CGColorSpace(name: CGColorSpace.sRGB)!,
    bitmapInfo: (opaque ? CGImageAlphaInfo.noneSkipLast : CGImageAlphaInfo.premultipliedLast).rawValue)!
  NSGraphicsContext.current = NSGraphicsContext(cgContext: ctx, flipped: false)
  image.draw(in: NSRect(x: 0, y: 0, width: size, height: size))
  let data = NSBitmapImageRep(cgImage: ctx.makeImage()!).representation(using: .png, properties: [:])!
  try data.write(to: URL(fileURLWithPath: path))
}

func write(_ text: String, to path: String) throws {
  try FileManager.default.createDirectory(atPath: (path as NSString).deletingLastPathComponent, withIntermediateDirectories: true)
  try text.write(toFile: path, atomically: true, encoding: .utf8)
}

func remove(_ path: String) { try? FileManager.default.removeItem(atPath: path) }

// --- iOS ---------------------------------------------------------------------

let assets = "ios/App/App/Assets.xcassets"
try png(#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 199 199">\#(tile(radius: 0))</svg>"#, size: 1024, opaque: true, to: "\(assets)/AppIcon.appiconset/AppIcon-512@2x.png")

// The launch storyboard aspect-fills this square, so the tile lands ~110 pt wide on a phone.
func launch(_ background: String) -> String {
  let side = 2732.0, t = 330.0
  return #"<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 \#(side) \#(side)"><rect width="\#(side)" height="\#(side)" fill="\#(background)"/><g transform="translate(\#((side - t) / 2) \#((side - t) / 2)) scale(\#(t / 199))">\#(tile(radius: 24))</g></svg>"#
}
let splash = "\(assets)/Splash.imageset"
for f in ["splash-2732x2732.png", "splash-2732x2732-1.png", "splash-2732x2732-2.png"] { remove("\(splash)/\(f)") }
try png(launch(canvas.light), size: 2732, opaque: true, to: "\(splash)/splash.png")
try png(launch(canvas.dark), size: 2732, opaque: true, to: "\(splash)/splash-dark.png")
try write(#"""
{
  "images" : [
    { "idiom" : "universal", "filename" : "splash.png" },
    { "idiom" : "universal", "filename" : "splash-dark.png", "appearances" : [ { "appearance" : "luminosity", "value" : "dark" } ] }
  ],
  "info" : { "version" : 1, "author" : "xcode" }
}
"""#, to: "\(splash)/Contents.json")

// --- Android -----------------------------------------------------------------

let res = "android/app/src/main/res"

/// The leg as vector paths, centered in a `box`-dp viewport at `height` dp tall.
func legVector(box: Double, height: Double, color: String) -> String {
  let s = height / legH
  return #"""
      <group android:scaleX="\#(s)" android:scaleY="\#(s)" android:translateX="\#((box - legW * s) / 2)" android:translateY="\#((box - height) / 2)">
          <path android:fillColor="\#(color)" android:pathData="\#(leg)"/>
      </group>
  """#
}

// Adaptive icon: 108 dp canvas, of which a 72 dp circle-to-square shows; the leg
// keeps the favicon's proportion of that (149 / 199).
let adaptiveLeg = 72 * legH / 199
for (name, color) in [("ic_launcher_foreground", "#FFFFFF"), ("ic_launcher_monochrome", "#000000")] {
  try write(#"""
  <?xml version="1.0" encoding="utf-8"?>
  <!-- Generated by mobile/scripts/icons.swift -->
  <vector xmlns:android="http://schemas.android.com/apk/res/android"
      android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">
  \#(legVector(box: 108, height: adaptiveLeg, color: color))
  </vector>
  """#, to: "\(res)/drawable/\(name).xml")
}
for name in ["ic_launcher", "ic_launcher_round"] {
  try write(#"""
  <?xml version="1.0" encoding="utf-8"?>
  <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
      <background android:drawable="@color/ic_launcher_background"/>
      <foreground android:drawable="@drawable/ic_launcher_foreground"/>
      <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
  </adaptive-icon>
  """#, to: "\(res)/mipmap-anydpi-v26/\(name).xml")
}
try write(#"""
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">\#(teal)</color>
</resources>
"""#, to: "\(res)/values/ic_launcher_background.xml")
remove("\(res)/drawable-v24/ic_launcher_foreground.xml")
remove("\(res)/drawable/ic_launcher_background.xml") // the template's grid; the color above replaces it

// Android 7 launchers take bitmaps: the rounded tile and the round one.
for (dir, px) in [("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)] {
  remove("\(res)/mipmap-\(dir)/ic_launcher_foreground.png")
  try png(#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="-8 -8 215 215">\#(tile(radius: 24))</svg>"#, size: px, opaque: false, to: "\(res)/mipmap-\(dir)/ic_launcher.png")
  try png(#"<svg xmlns="http://www.w3.org/2000/svg" viewBox="-8 -8 215 215">\#(tile(radius: nil))</svg>"#, size: px, opaque: false, to: "\(res)/mipmap-\(dir)/ic_launcher_round.png")
}

// Launch screen: the brand tile on the page color, drawn as vectors, so the
// per-density splash PNGs go.
for dir in ["drawable", "drawable-land-hdpi", "drawable-land-mdpi", "drawable-land-xhdpi", "drawable-land-xxhdpi", "drawable-land-xxxhdpi",
            "drawable-port-hdpi", "drawable-port-mdpi", "drawable-port-xhdpi", "drawable-port-xxhdpi", "drawable-port-xxxhdpi"] {
  remove("\(res)/\(dir)/splash.png")
  if dir != "drawable" { remove("\(res)/\(dir)") }
}
try write(#"""
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/scripts/icons.swift -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="112dp" android:height="112dp" android:viewportWidth="199" android:viewportHeight="199">
    <path android:fillColor="\#(teal)" android:pathData="M24,0h151a24,24 0,0 1,24 24v151a24,24 0,0 1,-24 24h-151a24,24 0,0 1,-24 -24v-151a24,24 0,0 1,24 -24z"/>
    <group android:translateX="55" android:translateY="26">
        <path android:fillColor="#FFFFFF" android:pathData="\#(leg)"/>
    </group>
</vector>
"""#, to: "\(res)/drawable/splash_mark.xml")
try write(#"""
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by mobile/scripts/icons.swift -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/splash_background"/>
    <item android:drawable="@drawable/splash_mark" android:gravity="center" android:width="112dp" android:height="112dp"/>
</layer-list>
"""#, to: "\(res)/drawable/splash.xml")
for (dir, color) in [("values", canvas.light), ("values-night", canvas.dark)] {
  try write(#"""
  <?xml version="1.0" encoding="utf-8"?>
  <resources>
      <color name="splash_background">\#(color)</color>
  </resources>
  """#, to: "\(res)/\(dir)/splash.xml")
}

print("Icons and launch screens written for iOS and Android.")
